In [5]:
import numpy as np

In [6]:
mylist = [[1,2,3],[1,2,3]]

In [7]:
mylist = np.array(mylist) #numpy array contain only single data type if you are add another then whole array will change into higher data type

In [8]:
print(mylist)

[[1 2 3]
 [1 2 3]]


In [9]:
mylist.ndim  # it return no of rows 

2

In [10]:
mylist.shape  # it return dimention of np array n*m

(2, 3)

In [11]:
arr= np.zeros(5)  # return 1d np-array with 0
print(arr)

[0. 0. 0. 0. 0.]


In [12]:
arr = np.zeros((2,5))  # return 2d np-array with 0
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
arr = np.ones(5)  # return 1d np-array with 1
print(arr)

[1. 1. 1. 1. 1.]


In [14]:
arr= np.ones((5,2))   # return 1d np-array with 0

In [15]:
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
arr= np.eye(5)  # return 2d np-array of size 5*5 with all diagonal value = 1 and other = 0
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
arr = np.eye(3,6)  # return 2d np-array of size 5*5 with all diagonal value = 1 starting from 0,0 index and other = 0

In [18]:
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [19]:
arr = np.diag([1,2,3,4])    # return 2d np-array of size of the size of passed array with all diagonal value = element in passed array  and other = 0
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
print(np.diag(arr))  # return diagonal of np-array

[1 2 3 4]


In [21]:
rand_arr = np.random.randint(1,15,4)  #return np-array (starting value, end value-1 , size) and size may be nd
print(rand_arr)

[ 4  3  3 10]


In [22]:
rand_arr = np.random.rand(4)  #return np-array size 4 and element value between 0-1 randomly
print(rand_arr)

[0.77202214 0.49299812 0.26456055 0.33186962]


In [23]:
rand_arr = np.random.rand(4,5)  #return np-array size 4*5 and element value between 0-1 randomly
print(rand_arr)

[[0.40831199 0.1736365  0.49909347 0.07720075 0.74500893]
 [0.74456631 0.02105093 0.56380021 0.38419611 0.83071493]
 [0.93119467 0.67472648 0.80944339 0.29388451 0.94165346]
 [0.94647509 0.22298824 0.02881034 0.87016734 0.05203942]]


In [24]:
rand_arr = np.random.randn(4)   #return np-array size 4 and element value between -1 - 1 randomly
print(rand_arr)

[1.70647828 0.55427012 0.15877127 1.27265031]


In [25]:
rand_arr = np.random.randn(4,5)  #return np-array size 4*5 and element value between -1 - 1 randomly
print(rand_arr)

[[ 1.11435379  1.56650114 -0.22240889  0.35786991  0.38749242]
 [ 0.75529062  1.71334551 -0.0722715  -1.52576665  0.56404288]
 [ 0.23734549  1.13278827  1.13582817 -1.63278004  1.09608588]
 [ 1.10935823 -0.19802869  1.09234948  0.50298548 -1.02533054]]


In [26]:
np.mean(rand_arr)  # return mean of the value of all elements of np-array

0.404452548139696

In [27]:
arr = np.random.randint(1,100,20)
arr

array([56, 22, 52, 98, 36,  4, 92,  6, 23, 23,  2,  6, 33, 99, 83, 84, 24,
       80, 65, 23])

In [28]:
arr.shape


(20,)

In [29]:
arr = arr.reshape(2,10)   # return the array with the passed n*m size and the size array size should equal to n*m
arr

array([[56, 22, 52, 98, 36,  4, 92,  6, 23, 23],
       [ 2,  6, 33, 99, 83, 84, 24, 80, 65, 23]])

In [30]:
arr.shape

(2, 10)

In [31]:
arr.ndim

2

In [32]:
arr = arr.reshape(20)

In [33]:
arr

array([56, 22, 52, 98, 36,  4, 92,  6, 23, 23,  2,  6, 33, 99, 83, 84, 24,
       80, 65, 23])

In [34]:
arr = np.random.randint(1,100,50)
arr = arr.reshape(10,5)
arr

array([[70, 55, 20, 27, 35],
       [28, 21,  8, 12, 26],
       [39, 85, 19, 55, 51],
       [95,  4, 46, 30, 30],
       [18, 30,  8, 18, 64],
       [24, 94, 31, 93, 87],
       [28, 28, 35, 73, 10],
       [48,  8, 63, 97, 63],
       [50, 71, 14, 88, 30],
       [22, 45, 96, 11, 79]])

In [35]:
arr.ndim

2

In [36]:
arr = arr.reshape(2,5,5)

In [37]:
arr

array([[[70, 55, 20, 27, 35],
        [28, 21,  8, 12, 26],
        [39, 85, 19, 55, 51],
        [95,  4, 46, 30, 30],
        [18, 30,  8, 18, 64]],

       [[24, 94, 31, 93, 87],
        [28, 28, 35, 73, 10],
        [48,  8, 63, 97, 63],
        [50, 71, 14, 88, 30],
        [22, 45, 96, 11, 79]]])

In [38]:
arr = np.reshape(25,-1)
arr

array([25])

In [39]:
arr

array([25])

In [40]:
arr = np.random.randint(1,100,50)
arr = arr.reshape(10,5)
arr

array([[22, 19, 89, 16, 59],
       [10, 58, 25, 96, 66],
       [34, 17, 32, 70, 67],
       [29, 19, 61, 84, 43],
       [15, 52, 31,  7, 98],
       [56,  4, 49,  8, 43],
       [42, 74,  2, 76, 56],
       [71, 30, 49,  6, 70],
       [83, 28, 71, 92, 48],
       [63, 64, 41, 11, 72]])

In [41]:
arr = arr.reshape(5,-1)  #Here -1 indicate rest possible size
arr

array([[22, 19, 89, 16, 59, 10, 58, 25, 96, 66],
       [34, 17, 32, 70, 67, 29, 19, 61, 84, 43],
       [15, 52, 31,  7, 98, 56,  4, 49,  8, 43],
       [42, 74,  2, 76, 56, 71, 30, 49,  6, 70],
       [83, 28, 71, 92, 48, 63, 64, 41, 11, 72]])

In [42]:
arr = arr.reshape(-1,5)
arr

array([[22, 19, 89, 16, 59],
       [10, 58, 25, 96, 66],
       [34, 17, 32, 70, 67],
       [29, 19, 61, 84, 43],
       [15, 52, 31,  7, 98],
       [56,  4, 49,  8, 43],
       [42, 74,  2, 76, 56],
       [71, 30, 49,  6, 70],
       [83, 28, 71, 92, 48],
       [63, 64, 41, 11, 72]])

In [43]:
arr = np.random.randint(1,110, 20)
arr

array([ 43,  69,  63, 109,  98,  67,  28,  10,  63,  78,  15, 107,  56,
        94,  88,  73, 104,  61,  38, 100])

In [44]:
np.random.seed(13)#same random array
arr = np.random.randint(1,110,20)
arr

array([ 83,  49,  75,  17, 103,  99,  26, 109,  59, 100,  27,  67,  47,
        55, 102,  78,  75,  74,  76,  53])

In [45]:
arr.size

20

In [46]:
index = arr[1]
print(index)
arr = arr[0:-1]
arr

49


array([ 83,  49,  75,  17, 103,  99,  26, 109,  59, 100,  27,  67,  47,
        55, 102,  78,  75,  74,  76])

In [47]:
myarr = np.array([[1,2,3],[1,2,3],[1,2,3]])
myarr


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
myarr[0][2]

3

In [49]:
myarr[1,2]

3

In [50]:
myarr



array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [51]:
myarr[0:2,0:2]

array([[1, 2],
       [1, 2]])

In [52]:
thisIsview = myarr[:1, :1]
thisIsview

array([[1]])

In [53]:
thisIsview[0,0] = 0
myarr

array([[0, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
thisIsview

array([[0]])

In [55]:
thisIscopy = myarr.copy()
thisIscopy

array([[0, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
thisIscopy[0][1] = 0
thisIscopy

array([[0, 0, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [57]:
myarr

array([[0, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [58]:
arangeArr = np.arange(1,11)
arangeArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr>5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [60]:
arangeArr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
istrue = arangeArr>5

In [62]:
istrue

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
arangeArr[istrue]

array([ 6,  7,  8,  9, 10])

In [64]:
arangeArr[arangeArr%2==0]

array([ 2,  4,  6,  8, 10])

In [65]:
arangeArr[arangeArr%2==0] = 0

In [66]:
arangeArr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [67]:
arangeArr*5

array([ 5,  0, 15,  0, 25,  0, 35,  0, 45,  0])

In [68]:
arangeArr+5

array([ 6,  5,  8,  5, 10,  5, 12,  5, 14,  5])

In [69]:
arr1 = np.array([[1,2,3],[1,2,3]])
arr2= np.array([[1,2,3],[1,2,3]])
arr1+arr2

array([[2, 4, 6],
       [2, 4, 6]])

In [70]:
np.random.seed(123)
matrix1 = np.random.randint(1,12,9).reshape(3,3)
matrix2 = np.random.randint(5,15,9).reshape(3,3)

In [71]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [72]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [73]:
matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [74]:
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

In [75]:
np.min(matrix1)

2

In [76]:
np.argmin(matrix1)

3

In [77]:
np.max(matrix1)

11

In [78]:
np.argmax(matrix1)

5

In [79]:
np.sqrt(matrix1)

array([[1.73205081, 1.73205081, 2.64575131],
       [1.41421356, 2.        , 3.31662479],
       [3.16227766, 2.64575131, 1.41421356]])

In [80]:
np.exp(arr)

array([1.11286375e+36, 1.90734657e+21, 3.73324200e+32, 2.41549528e+07,
       5.39922761e+44, 9.88903032e+42, 1.95729609e+11, 2.17820388e+47,
       4.20121040e+25, 2.68811714e+43, 5.32048241e+11, 1.25236317e+29,
       2.58131289e+20, 7.69478527e+23, 1.98626484e+44, 7.49841700e+33,
       3.73324200e+32, 1.37338298e+32, 1.01480039e+33])

In [81]:
np.sin(arr)

array([ 0.96836446, -0.95375265, -0.38778164, -0.96139749,  0.62298863,
       -0.99920683,  0.76255845,  0.81674261,  0.63673801, -0.50636564,
        0.95637593, -0.85551998,  0.12357312, -0.99975517,  0.99482679,
        0.51397846, -0.38778164, -0.98514626,  0.56610764])

In [82]:
np.cos(arr)

array([ 0.24954012,  0.30059254,  0.92175127, -0.27516334, -0.78223089,
        0.03982088,  0.64691932, -0.57700218, -0.77108022,  0.86231887,
       -0.29213881, -0.5177698 , -0.99233547,  0.02212676,  0.1015857 ,
       -0.85780309,  0.92175127,  0.17171734,  0.82433133])

In [83]:
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [84]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
aarr4 = np.array([1,2,3,0], dtype = 'bool')
aarr4

array([ True,  True,  True, False])

In [86]:
for i in aarr4:
    print(i)

True
True
True
False


In [87]:
np.sum(matrix1)

49

In [88]:
matrix1.sum()

49

In [89]:
np.min(matrix1,axis=1)

array([3, 2, 2])

In [90]:
np.min(matrix1,axis=0)

array([2, 3, 2])

In [91]:
np.cumsum(matrix1)

array([ 3,  6, 13, 15, 19, 30, 40, 47, 49], dtype=int32)

In [92]:
np.cumsum(matrix1, axis =1)

array([[ 3,  6, 13],
       [ 2,  6, 17],
       [10, 17, 19]], dtype=int32)

In [93]:
np.prod(matrix1)

776160

In [94]:
np.prod(matrix1, axis = 1)

array([ 63,  88, 140])

In [95]:
np.random.shuffle(matrix1)

In [96]:
matrix1

array([[ 2,  4, 11],
       [10,  7,  2],
       [ 3,  3,  7]])

In [97]:
np.unique(arr)

array([ 17,  26,  27,  47,  49,  55,  59,  67,  74,  75,  76,  78,  83,
        99, 100, 102, 103, 109])

In [98]:
np.unique(matrix1)

array([ 2,  3,  4,  7, 10, 11])

In [99]:
np.unique(matrix1).size

6

In [100]:
np.unique(matrix1, return_index=True, return_counts= True)

(array([ 2,  3,  4,  7, 10, 11]),
 array([0, 6, 1, 4, 3, 2], dtype=int64),
 array([2, 2, 1, 2, 1, 1], dtype=int64))

In [101]:
np.hstack((matrix1,matrix2))

array([[ 2,  4, 11,  5,  6, 14],
       [10,  7,  2,  5,  5, 14],
       [ 3,  3,  7,  8,  9,  5]])

In [102]:
matrix1

array([[ 2,  4, 11],
       [10,  7,  2],
       [ 3,  3,  7]])

In [103]:
np.vstack((matrix1,matrix2))

array([[ 2,  4, 11],
       [10,  7,  2],
       [ 3,  3,  7],
       [ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [ ]:
%timeit 1+2

In [ ]:
%%timeit 
1+3
2+4

In [ ]:
np.concatenate([matrix1,matrix2])

In [ ]:
a1,a2,a3 = np.split(matrix1,[2,4])

In [ ]:
print(a1)

In [ ]:
a2

In [ ]:
a3

In [ ]:
a1,a2,a3,a4 = np.split(matrix1,[2,4,5])

In [ ]:
print(a1)
print(a2)
print(a3)
print(a4)

In [ ]:
#hsplit vsplit dsplit
#hconcatenate vconcatenate dconcatenate 